# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install pip dependency
        run: pip install beautifulsoup4
      - name: Build
        run: npm run build
      - name: Presite
        run: npm run presite
      - name: Post process pages
        run: npm run post-process
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: "./.presite"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # FTP credentials
          host: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          user: ${{ secrets.FTP_USER }}
          pass: ${{ secrets.FTP_PASS }}
          # lftp settings
          onlyNewer: true
          settings: "sftp:auto-confirm=yes"
          # Mirror command options
          localDir: "."
          remoteDir: "/var/www/html/vite.r5.ro/"
          reverse: true
          ignoreFile: ".lftp_ignore"
          options: "--verbose"
